<!DOCTYPE html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>{{ $report['report']['title'] }}</title>
  <style>
  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    color: #333;
    font-size: 12px;
  }

  .header {
    padding: 10px;
    border-bottom: 1px solid #ddd;
    margin-bottom: 20px;
  }

  .logo {
    max-height: 60px;
  }

  h1 {
    font-size: 24px;
    margin: 0 0 5px 0;
    color: #003366;
  }

  h2 {
    font-size: 18px;
    margin: 15px 0 5px 0;
    color: #003366;
    border-bottom: 1px solid #eee;
    padding-bottom: 5px;
  }

  h3 {
    font-size: 14px;
    margin: 15px 0 5px 0;
    color: #003366;
  }

  .report-meta {
    margin-bottom: 20px;
    font-size: 12px;
  }

  .report-meta table {
    width: 100%;
  }

  .report-meta td {
    padding: 3px 10px 3px 0;
  }

  .report-meta td:first-child {
    font-weight: bold;
    width: 150px;
  }

  .summary-section {
    margin-bottom: 20px;
  }

  .summary-box {
    border: 1px solid #ddd;
    padding: 15px;
    margin-bottom: 15px;
    background-color: #f9f9f9;
  }

  .stat-grid {
    display: flex;
    flex-wrap: wrap;
    margin: 0 -10px;
  }

  .stat-box {
    flex: 1;
    min-width: 120px;
    border: 1px solid #ddd;
    padding: 10px;
    margin: 10px;
    text-align: center;
    background-color: #f9f9f9;
  }

  .stat-value {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 5px;
    color: #003366;
  }

  .stat-label {
    font-size: 12px;
    color: #666;
  }

  table.data-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
  }

  table.data-table th {
    background-color: #003366;
    color: white;
    padding: 8px;
    text-align: left;
    font-size: 12px;
  }

  table.data-table td {
    padding: 8px;
    border-bottom: 1px solid #ddd;
    font-size: 11px;
  }

  table.data-table tr:nth-child(even) {
    background-color: #f9f9f9;
  }

  .severity-critical {
    color: #d9534f;
    font-weight: bold;
  }

  .severity-high {
    color: #f0ad4e;
    font-weight: bold;
  }

  .severity-medium {
    color: #5bc0de;
  }

  .severity-low {
    color: #5cb85c;
  }

  .footer {
    margin-top: 30px;
    padding-top: 10px;
    border-top: 1px solid #ddd;
    font-size: 10px;
    text-align: center;
    color: #777;
  }

  .page-break {
    page-break-after: always;
  }
  </style>
</head>

<body>
  <div class="header">
    <table width="100%">
      <tr>
        <td>
          <h1>Security Report</h1>
          <h2>{{ $report['report']['title'] }}</h2>
        </td>
        <td style="text-align: right;">
          <img src="{{ public_path('images/logo.png') }}" class="logo" />
        </td>
      </tr>
    </table>
  </div>

  <div class="report-meta">
    <table>
      <tr>
        <td>Report ID:</td>
        <td>{{ $report['report']['id'] }}</td>
      </tr>
      <tr>
        <td>Generated:</td>
        <td>{{ $report['report']['created_at'] }}</td>
      </tr>
      <tr>
        <td>Generated By:</td>
        <td>{{ $report['report']['generated_by'] }}</td>
      </tr>
      <tr>
        <td>Tenant:</td>
        <td>{{ $report['report']['tenant'] }}</td>
      </tr>
      <tr>
        <td>Template:</td>
        <td>{{ $report['report']['template_name'] }}</td>
      </tr>
      <tr>
        <td>Date Range:</td>
        <td>
          {{ $report['report']['date_range']['from'] }} to
          {{ $report['report']['date_range']['to'] }}
        </td>
      </tr>
    </table>
  </div>

  @if(!empty($report['report']['description']))
  <div class="summary-box">
    <h3>Description</h3>
    <p>{{ $report['report']['description'] }}</p>
  </div>
  @endif

  <!-- Executive Summary Section -->
  <h2>Executive Summary</h2>
  <div class="summary-section">
    <div class="stat-grid">
      <div class="stat-box">
        <div class="stat-value">{{ $report['summary']['total_events'] }}</div>
        <div class="stat-label">Total Events</div>
      </div>
      <div class="stat-box">
        <div class="stat-value">{{ $report['summary']['total_alerts'] }}</div>
        <div class="stat-label">Security Alerts</div>
      </div>

      @if(isset($report['summary']['critical_alerts']))
      <div class="stat-box">
        <div class="stat-value severity-critical">{{ $report['summary']['critical_alerts'] }}</div>
        <div class="stat-label">Critical Alerts</div>
      </div>
      @endif
    </div>
  </div>

  <!-- Severity Breakdown -->
  @if(!empty($report['summary']['severity_breakdown']))
  <h2>Severity Breakdown</h2>
  <table class="data-table">
    <thead>
      <tr>
        <th>Severity</th>
        <th>Count</th>
        <th>Percentage</th>
      </tr>
    </thead>
    <tbody>
      @php
      $totalEvents = $report['summary']['total_events'];
      @endphp

      @foreach($report['summary']['severity_breakdown'] as $severity => $count)
      <tr>
        <td class="severity-{{ strtolower($severity) }}">{{ $severity }}</td>
        <td>{{ $count }}</td>
        <td>{{ $totalEvents > 0 ? round(($count / $totalEvents) * 100, 1) : 0 }}%</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endif

  <!-- Event Types -->
  @if(!empty($report['summary']['event_types']))
  <h2>Event Types</h2>
  <table class="data-table">
    <thead>
      <tr>
        <th>Event Type</th>
        <th>Count</th>
        <th>Percentage</th>
      </tr>
    </thead>
    <tbody>
      @php
      $totalEvents = $report['summary']['total_events'];
      @endphp

      @foreach($report['summary']['event_types'] as $type => $count)
      <tr>
        <td>{{ $type }}</td>
        <td>{{ $count }}</td>
        <td>{{ $totalEvents > 0 ? round(($count / $totalEvents) * 100, 1) : 0 }}%</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endif

  <!-- Page Break -->
  <div class="page-break"></div>

  <!-- Security Events -->
  @if(!empty($report['data']['events']))
  <h2>Security Events</h2>
  <table class="data-table">
    <thead>
      <tr>
        <th>Time</th>
        <th>Type</th>
        <th>Severity</th>
        <th>User</th>
        <th>IP Address</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      @foreach($report['data']['events'] as $event)
      <tr>
        <td>{{ $event['timestamp'] ?? 'N/A' }}</td>
        <td>{{ $event['event_type'] ?? 'N/A' }}</td>
        <td class="severity-{{ strtolower($event['severity'] ?? 'low') }}">{{ $event['severity'] ?? 'N/A' }}</td>
        <td>{{ $event['user'] ?? 'N/A' }}</td>
        <td>{{ $event['ip_address'] ?? 'N/A' }}</td>
        <td>{{ $event['description'] ?? 'N/A' }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endif

  <!-- Security Alerts -->
  @if(!empty($report['data']['alerts']))
  <h2>Security Alerts</h2>
  <table class="data-table">
    <thead>
      <tr>
        <th>Time</th>
        <th>Title</th>
        <th>Severity</th>
        <th>Status</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      @foreach($report['data']['alerts'] as $alert)
      <tr>
        <td>{{ $alert['created_at'] ?? 'N/A' }}</td>
        <td>{{ $alert['title'] ?? 'N/A' }}</td>
        <td class="severity-{{ strtolower($alert['severity'] ?? 'low') }}">{{ $alert['severity'] ?? 'N/A' }}</td>
        <td>{{ $alert['status'] ?? 'N/A' }}</td>
        <td>{{ $alert['description'] ?? 'N/A' }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endif

  <div class="footer">
    <p>This report is confidential and intended for authorized personnel only.</p>
    <p>Generated on {{ date('Y-m-d H:i:s') }} by TSMS Security Reporting System</p>
    <p>Page {PAGENO} of {nb}</p>
  </div>
</body>

</html>